server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always  # 스키마 및 데이터 초기화 실행
      encoding: UTF-8
      data-locations:
        - classpath:data.sql
        - classpath:extra-data.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true

file:
  upload-dir: D:/uploads/final


logging:
  level:
    root: INFO  # 전체 기본 로그 레벨
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    org.springframework.security: INFO