server:
  port: 9090


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always  # 스키마 및 데이터 초기화 실행
      encoding: UTF-8
      data-locations:
        - classpath:data.sql
        - classpath:extra-data.sql
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations: classpath:mappers/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org.springframework.security: INFO